/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : MQX1.c
**     Project     : ProcessorExpert
**     Processor   : MKL46Z256VMC4
**     Version     : Component 01.098, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-07-26, 06:03, # CodeGen: 47
**     Abstract    :
**         MQX Lite RTOS Adapter component.
**     Settings    :
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file MQX1.c
** @version 01.00
** @brief
**         MQX Lite RTOS Adapter component.
*/         
/*!
**  @addtogroup MQX1_module MQX1 module documentation
**  @{
*/         

/* MODULE MQX1. */

#include "MQX1.h"
#include "mqx_tasks.h"



/* Task stacks definition */
uint8_t LED_Task1_task_stack[LED_TASK1_TASK_STACK_SIZE];
uint8_t LED_Task2_task_stack[LED_TASK2_TASK_STACK_SIZE];
uint8_t LED_Task3_task_stack[LED_TASK3_TASK_STACK_SIZE];
uint8_t LED_Task4_task_stack[LED_TASK4_TASK_STACK_SIZE];
uint8_t SW2_Task5_task_stack[SW2_TASK5_TASK_STACK_SIZE];
uint8_t SW4_Task6_task_stack[SW4_TASK6_TASK_STACK_SIZE];

/* Task stacks array of pointers */
const uint8_t * mqx_task_stack_pointers[] = {
/* "LED_Task1" task                    */  LED_Task1_task_stack,
/* "LED_Task2" task                    */  LED_Task2_task_stack,
/* "LED_Task3" task                    */  LED_Task3_task_stack,
/* "LED_Task4" task                    */  LED_Task4_task_stack,
/* "SW2_Task5" task                    */  SW2_Task5_task_stack,
/* "SW4_Task6" task                    */  SW4_Task6_task_stack,
/* Stack array end                     */  NULL
};

/* Kernel Data Structure */
volatile KERNEL_DATA_STRUCT            _mqx_kernel_data_struct;
#define __KERNEL_DATA_START            (pointer)(&_mqx_kernel_data_struct)
#define __KERNEL_DATA_END              (pointer)((uchar_ptr)&_mqx_kernel_data_struct + sizeof(_mqx_kernel_data_struct))

/* Task ready queue */
READY_Q_STRUCT                         mqx_static_ready_queue[MQX_READY_QUEUE_ITEMS];

/* Table of 'C' handlers for interrupts. */
INTERRUPT_TABLE_STRUCT                 mqx_static_isr_table[MQX_INTERRUPT_TABLE_ITEMS];


/* Interrupt stack */
uint8_t mqx_interrupt_stack[MQX_INTERRUPT_STACK_SIZE + PSP_STACK_ALIGNMENT + 1];
/* Idle task stack */
uint8_t mqx_idle_task_stack[sizeof(TD_STRUCT) + PSP_IDLE_STACK_SIZE + PSP_STACK_ALIGNMENT + 1];
/* System stack */
uint8_t mqx_system_stack[PSP_MINSTACKSIZE + PSP_STACK_ALIGNMENT + 1];

/* MQX Lite initialization structure */
const MQXLITE_INITIALIZATION_STRUCT  MQX_init_struct =
{
/* PROCESSOR NUMBER                 */  1,
/* START OF KERNEL MEMORY           */  __KERNEL_DATA_START,
/* END OF KERNEL MEMORY             */  __KERNEL_DATA_END,
/* MQX_HARDWARE_INTERRUPT_LEVEL_MAX */  1,
/* INTERRUPT STACK SIZE             */  sizeof(mqx_interrupt_stack),
/* INTERRUPT STACK LOCATION         */  mqx_interrupt_stack,
/* IDLE_TASK STACK SIZE             */  sizeof(mqx_idle_task_stack),
/* IDLE_TASK STACK_LOCATION         */  mqx_idle_task_stack,
/* TASK TEMPLATE LIST               */  (TASK_TEMPLATE_STRUCT_PTR)&MQX_template_list[0]
};

/*
** ===================================================================
**     Method      :  MQX1_OnCounterRestart (component MQXLite)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void SystemTimer1_OnCounterRestart(LDD_TUserData *UserDataPtr)
{
    _time_notify_kernel();
}


/* Function returns number of ticks per second for system timer */
uint32_t  SystemTimer1_GetTicsPerSecond(LDD_TDeviceData *DeviceDataPtr)
{
    uint32_t input_frequency;
    uint32_t period_ticks;

    /* Parameter DeviceDataPtr is not used, suppress unused argument warning */
    (void)DeviceDataPtr;
    input_frequency = SystemTimer1_GetInputFrequency(NULL);
    SystemTimer1_GetPeriodTicks(NULL, &period_ticks);
    return input_frequency / (period_ticks);
}



/* END MQX1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.06]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
