/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : task_template_list.c
**     Project     : ProcessorExpert
**     Processor   : MKL46Z256VMC4
**     Version     : Component 01.098, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-07-26, 06:03, # CodeGen: 47
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file task_template_list.c                                                  
** @version 01.00
*/         
/*!
**  @addtogroup task_template_list_module task_template_list module documentation
**  @{
*/         

#include "task_template_list.h"
#include "mqx_tasks.h"

#define TASK_TEMPLATE_LIST_END         {0, 0, 0, 0, 0, 0, 0}

/* MQX task template list */
const TASK_TEMPLATE_STRUCT MQX_template_list[] =
{
  /* Task: LED_Task1 */
  {
  /* Task number                      */  LED_TASK1_TASK,
  /* Entry point                      */  (TASK_FPTR)OR_LED_task,
  /* Stack size                       */  LED_TASK1_TASK_STACK_SIZE,
  /* Task priority                    */  8U,
  /* Task name                        */  "led_task1",
  /* Task attributes                  */  (MQX_AUTO_START_TASK),
  /* Task parameter                   */  (uint32_t)(0)
  },
  /* Task: LED_Task2 */
  {
  /* Task number                      */  LED_TASK2_TASK,
  /* Entry point                      */  (TASK_FPTR)YEL_LED_task,
  /* Stack size                       */  LED_TASK2_TASK_STACK_SIZE,
  /* Task priority                    */  8U,
  /* Task name                        */  "led_task2",
  /* Task attributes                  */  (0),
  /* Task parameter                   */  (uint32_t)(0)
  },
  /* Task: LED_Task3 */
  {
  /* Task number                      */  LED_TASK3_TASK,
  /* Entry point                      */  (TASK_FPTR)RED_LED_task,
  /* Stack size                       */  LED_TASK3_TASK_STACK_SIZE,
  /* Task priority                    */  8U,
  /* Task name                        */  "led_task3",
  /* Task attributes                  */  (0),
  /* Task parameter                   */  (uint32_t)(0)
  },
  /* Task: LED_Task4 */
  {
  /* Task number                      */  LED_TASK4_TASK,
  /* Entry point                      */  (TASK_FPTR)GRE_LED_task,
  /* Stack size                       */  LED_TASK4_TASK_STACK_SIZE,
  /* Task priority                    */  8U,
  /* Task name                        */  "led_task4",
  /* Task attributes                  */  (0),
  /* Task parameter                   */  (uint32_t)(0)
  },
  /* Task: SW2_Task5 */
  {
  /* Task number                      */  SW2_TASK5_TASK,
  /* Entry point                      */  (TASK_FPTR)SW2_task,
  /* Stack size                       */  SW2_TASK5_TASK_STACK_SIZE,
  /* Task priority                    */  8U,
  /* Task name                        */  "sw2_task5",
  /* Task attributes                  */  (MQX_AUTO_START_TASK),
  /* Task parameter                   */  (uint32_t)(0)
  },
  /* Task: SW4_Task6 */
  {
  /* Task number                      */  SW4_TASK6_TASK,
  /* Entry point                      */  (TASK_FPTR)SW4_task,
  /* Stack size                       */  SW4_TASK6_TASK_STACK_SIZE,
  /* Task priority                    */  8U,
  /* Task name                        */  "sw4_task6",
  /* Task attributes                  */  (MQX_AUTO_START_TASK),
  /* Task parameter                   */  (uint32_t)(0)
  },
  TASK_TEMPLATE_LIST_END
};

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.06]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
